use_frameworks!

platform :ios, '9.0'

target 'iMRuby_Example' do
  pod 'iMRuby', :path => '../'

  target 'Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  end
  
  post_install do |installer|
    installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
      configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
  end
end
