name: Xcode - Build and Analyze

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          xcodebuild test-without-building -scheme iMRuby-Example -workspace Example/iMRuby.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.2' |xcpretty
